version: build-{build}
image: Visual Studio 2017

nuget:
  disable_publish_on_pr: true
pull_requests:
  do_not_increment_build_number: true
clone_folder: C:/Projects/CRoaring.Net

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:BUILD = "$($Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0"))"
install:
- cmd: git submodule update --init --recursive

build_script:
- ps: mkdir "C:/Projects/CRoaring.Net/lib/CRoaring/build"
- ps: >-
    cd C:/Projects/CRoaring.Net/lib/CRoaring/build
    cmake -G"Visual Studio 15 2017" -DCMAKE_GENERATOR_PLATFORM=x64 ..
    cmake --build . --config Release --target roaring
- cmd: copy "C:/Projects/CRoaring.Net/lib/CRoaring/build/src/Release/roaring.dll" "C:/Projects/CRoaring.Net/src/CRoaring.Net/"
- cmd: copy "C:/Projects/CRoaring.Net/lib/CRoaring/build/src/Release/roaring.dll" "C:/Projects/CRoaring.Net/test/CRoaring.Net.Test/"
- ps: appveyor-retry dotnet restore Roaring.Net.sln -v Minimal /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: dotnet build CRoaring.Net.sln -c Release /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: dotnet pack "src\CRoaring.Net\CRoaring.Net.csproj" -c Release -o "../../artifacts" --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"

test_script:
- ps: dotnet C:/Projects/CRoaring.Net/test/CRoaring.Net.Test/CRoaring.Net.Test.csproj -c Release --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"

artifacts:
- path: artifacts/*.nupkg
  name: MyGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/rogueexception/api/v2/package
  api_key:
    secure: D+vW2O2LBf/iJb4f+q8fkyIW2VdIYIGxSYLWNrOD4BHlDBZQlJipDbNarWjUr2Kn
  symbol_server: https://www.myget.org/F/rogueexception/symbols/api/v2/package
  artifact: MyGet
  on:
    branch: master